### ISSUE TITLE
关于i18n

### ISSUE THREAD

**Issue by junity233** [unknown-o/kagamine#3]
建议使用 `jquery.i18n.properties` 之类的插件，把中文英文两套源代码合成一套，方便未来迭代。

**Comment by junity233** [comment]
不然每次都得改两遍，有点麻烦

**Comment by unknown-o** [comment]
感谢您的意见，本人已开始使用vue重写整个项目。完成后将支持i18n
[https://static-1.llilii.cn/web-app/kagamine-beta/#/](https://static-1.llilii.cn/web-app/kagamine-beta/#/)

**Comment by junity233** [comment]
![9U @0VCB~C3ZNU9TXB7P}OS](https://user-images.githubusercontent.com/59906925/189320852-156977d1-4bf3-44fc-94b2-d7524997884e.png)
